import { AllImage } from "@/assets/AllImge";
import Profile from "../components/dashboard/profile/Profile";
export type IAllUsers = {
  userID: string;
  name: string;
  email: string;
  number: string;
  dob: string;
  address: string;
  profile: string;
  amount: number;
  paymentMethod: string;
};

export const usersData: IAllUsers[] = [
  {
    userID: "1",
    name: "Kane Kooper",
    email: "kane@gmail.com",
    number: "+123 456 789",
    dob: "11/02/1996",
    address: "12 street, New York, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Debit Card ",
  },
  {
    userID: "2",
    name: "John Doe",
    email: "john.doe@example.com",
    number: "+123 456 7890",
    dob: "01/15/1985",
    address: "123 Main Street, Anytown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Credit Card",
  },
  {
    userID: "3",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    number: "+123 456 7891",
    dob: "05/20/1990",
    address: "456 Elm Street, Springfield, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "PayPal",
  },
  {
    userID: "4",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    number: "+123 456 7891",
    dob: "05/20/1990",
    address: "456 Elm Street, Springfield, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "PayPal",
  },
  {
    userID: "5",
    name: "User 31",
    email: "user31@example.com",
    number: "+123 456 7892",
    dob: "12/05/1988",
    address: "789 Maple Avenue, Smalltown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Venmo",
  },
  {
    userID: "6",
    name: "Emily Brown",
    email: "emily.brown@example.com",
    number: "+123 456 7894",
    dob: "11/02/1996",
    address: "12 Oak Lane, Smallville, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Bank Transfer",
  },
  {
    userID: "7",
    name: "Michael Miller",
    email: "michael.miller@example.com",
    number: "+123 456 7895",
    dob: "07/15/1988",
    address: "567 Pine Street, Rivertown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Stripe",
  },
  {
    userID: "8",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    number: "+123 456 7891",
    dob: "05/20/1990",
    address: "456 Elm Street, Springfield, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "PayPal",
  },
  {
    userID: "9",
    name: "User 31",
    email: "user31@example.com",
    number: "+123 456 7892",
    dob: "12/05/1988",
    address: "789 Maple Avenue, Smalltown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Venmo",
  },
  {
    userID: "10",
    name: "User 31",
    email: "user31@example.com",
    number: "+123 456 7892",
    dob: "12/05/1988",
    address: "789 Maple Avenue, Smalltown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Venmo",
  },
  {
    userID: "11",
    name: "Kane Kooper",
    email: "kane@gmail.com",
    number: "+123 456 789",
    dob: "11/02/1996",
    address: "12 street, New York, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Debit Card ",
  },
  {
    userID: "12",
    name: "John Doe",
    email: "john.doe@example.com",
    number: "+123 456 7890",
    dob: "01/15/1985",
    address: "123 Main Street, Anytown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Credit Card",
  },
  {
    userID: "13",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    number: "+123 456 7891",
    dob: "05/20/1990",
    address: "456 Elm Street, Springfield, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "PayPal",
  },
  {
    userID: "14",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    number: "+123 456 7891",
    dob: "05/20/1990",
    address: "456 Elm Street, Springfield, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "PayPal",
  },
  {
    userID: "15",
    name: "User 15",
    email: "user31@example.com",
    number: "+123 456 7892",
    dob: "12/05/1988",
    address: "789 Maple Avenue, Smalltown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Venmo",
  },
  {
    userID: "16",
    name: "Emily Brown",
    email: "emily.brown@example.com",
    number: "+123 456 7894",
    dob: "11/02/1996",
    address: "12 Oak Lane, Smallville, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Bank Transfer",
  },
  {
    userID: "17",
    name: "Michael Miller",
    email: "michael.miller@example.com",
    number: "+123 456 7895",
    dob: "07/15/1988",
    address: "567 Pine Street, Rivertown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Stripe",
  },
  {
    userID: "18",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    number: "+123 456 7891",
    dob: "05/20/1990",
    address: "456 Elm Street, Springfield, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "PayPal",
  },
  {
    userID: "19",
    name: "User 31",
    email: "user31@example.com",
    number: "+123 456 7892",
    dob: "12/05/1988",
    address: "789 Maple Avenue, Smalltown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Venmo",
  },
  {
    userID: "20",
    name: "User 31",
    email: "user31@example.com",
    number: "+123 456 7892",
    dob: "12/05/1988",
    address: "789 Maple Avenue, Smalltown, USA",
    profile: "",
    amount: 3.5,
    paymentMethod: "Venmo",
  },
];
